- change: added
  target: route
  breaking: false
  deprecated: false
  doc_only: false
  note: Adds POST /organization/users/{user_id}/roles to assign an organization role to a user and return the role assignment.
  paths: []
  date: '2026-02-20'
