- change: added
  target: route
  breaking: false
  deprecated: false
  doc_only: false
  note: New endpoint to delete a custom role from a project and return deletion confirmation.
  paths: []
  date: '2026-02-20'
